### ISSUE TITLE
Link to project?

### ISSUE THREAD

**Issue by giggsey** [IonBazan/composer-diff#15]
If links are enabled, could there be a link to the project too?

**Comment by IonBazan** [comment]
Hello @giggsey, thanks for the suggestion. This would actually quite useful but I'm not sure how this should be implemented. Do you think we should add a value to `--with-links` option allowing to specify which link to show (compare, release or project) or should we add a new parameter to display these project links in separate column/field?

Feel free to open a PR - contributions are welcome! 

PS. Don't be afraid of strict CI rules. I can help you deal with that afterwards 😉
