### ISSUE TITLE
Feature request: 3 dot syntax for diff in GithubGenerator

### ISSUE THREAD

**Issue by MrJamesEllis** [IonBazan/composer-diff#34]
Hi

Wondering if the three dot syntax for Github diffs could be supported in https://github.com/IonBazan/composer-diff/blob/main/src/Url/GithubGenerator.php#L23 - similar to the GitlabGenerator

Two dot: https://github.com/IonBazan/composer-diff/compare/v1.8.0..v1.9.0
Three dot: https://github.com/IonBazan/composer-diff/compare/v1.8.0...v1.9.0

The three-dot syntax shows a list of commits and file changes in tabs, which is useful for  review and ability to review a single commit quickly.

2-dots could be retained for BC, so maybe an option to the command to switch to 3 dots ?

See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons

Thanks!

**Comment by IonBazan** [comment]
I had no idea there are 2 different diff views on GitHub 🫢 
I think we can consider this a non-breaking change as it still shows a diff in the end - unless someone opposes. 

I just checked that both @renovatebot and @dependabot use the 3-dot URLs in PR descriptions. Let me implement this change.
